// ==================== 页面路由常量 ====================

export class RouteConstants {
  /**
   * 主页面
   */
  static readonly MAIN_PAGE: string = 'MainPage'
  /**
   * 首页
   */
  static readonly HOME: string = 'Home'
  /**
   * 我的页面
   */
  static readonly MINE: string = 'Mine'
  /**
   * Flutter 评估入口页面
   */
  static readonly EVALUATE_ENTRY: string = 'EvaluateEntry';
  /**
   * Flutter 测试页面
   */
  static readonly FLUTTER_TEST_PAGE: string = 'FlutterTestPage';
  /**
   * 富文本展开折叠
   */
  static readonly GRAPHICS: string = 'Graphics';
  /**
   * 富文本页面
   */

  static readonly RICH_TEXT_EXPAND: string = 'RichTextExpand';
  /**
   * 纯文本页面
   */

  static readonly TEXT_EXPAND: string = 'TextExpand';
  /**
   * Spine动画页面
   */
  static readonly SPINE_ANIMATION: string = 'SpineAnimation';
  /**
   * Spine示例1 - 加载动画
   */
  static readonly SPINE_EXAMPLE1: string = 'SpineExample1';
  /**
   * Spine示例2 - 加载网络动画
   */
  static readonly SPINE_NETWORK_EXAMPLE: string = 'SpineNetworkExample';
  /**
   * Spine示例3 - 加载JSON动画
   */
  static readonly SPINE_SINGLE_EXAMPLE: string = 'SpineSingleExample';
  /**
   * Spine示例4 - 加载骨骼动画
   */
  static readonly SPINE_EXAMPLE2: string = 'SpineExample2';
  /**
   * Spine示例5 - 加载沙盒动画
   */
  static readonly SPINE_EXAMPLE3: string = 'SpineExample3';
  /**
   * Spine示例6 - 其他
   */
  static readonly SPINE_EXAMPLE4: string = 'SpineExample4';
  /**
   * Spine示例6 - 基础示例
   */
  static readonly BASIC_EXAMPLE4: string = 'BasicExample';
  /**
   * Spine特殊动画
   */
  static readonly SPECIAL_ANIMATION: string = 'SpecialAnimation';
  /**
   * GridRowDemo
   */

  static readonly GIRD_ROW_DEMO: string = 'GridRowDemo';
  /**
   * 引用资源页面
   */
  static readonly REFERENCE_RES_PAGE: string = 'ReferenceResPage';
  /**
   * 食物订单页面
   */
  static readonly FOOD_PAGE: string = 'FoodPage';
  /**
   * 新闻页面
   */
  static readonly NEWS_PAGE: string = 'NewsPage';
  /**
   * 教育页面
   */
  static readonly EDUCATION_PAGE: string = 'EducationPage';
  /**
   * 购物页面
   */
  static readonly SHOP_PAGE: string = 'ShopPage';
  /**
   * 旅游页面
   */
  static readonly TRAVEL_PAGE: string = 'TravelPage';
  /**
   * samples页面
   */
  static readonly SAMPLES_PAGE: string = 'SamplesPage';
  /**
   * Api测试页面
   */
  static readonly API_TEST_COMMON_PAGE: string = 'ApiTestCommonPage'
  /**
   * 测试页面
   */
  static readonly MC_CHARTS_SAMPLES_PAGE: string = 'McChartsSamples';
  /**
   * 通用视频播放器示例页（CommonVideoPlayer）
   */
  static readonly COMMON_VIDEO_PLAYER_DEMO: string = 'CommonVideoPlayerDemo';
  /**
   * 弹窗队列（PopupDialogQueueManager）演示页
   */
  static readonly POPUP_DIALOG_QUEUE_DEMO: string = 'PopupDialogQueueDemoPage';
}