
// ==================== 页面路由常量 ====================

export class RouteConstants {

  /**
   * 主页面
   */
  static readonly MAIN_PAGE: string = 'MainPage'

  /**
   * 首页
   */
  static readonly HOME: string = 'Home'
  /**
   * 我的页面
   */
  static readonly MINE: string = 'Mine'
  /**
   * Flutter 评估入口页面
   */
  static readonly EVALUATE_ENTRY: string = 'EvaluateEntry';

  /**
   * Flutter 测试页面
   */
  static readonly FLUTTER_TEST_PAGE: string = 'FlutterTestPage';

}